spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        type:
          json_format_mapper: com.rmnnorbert.dentocrates.config.JacksonJsonFormatMapperCustom
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  web:
    resources:
        static-locations: classpath:/frontend/
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        operations-sorter:
            "method"
management:
  endpoints:
      web:
          exposure:
              include:
                  "*"
  health:
      db:
          enabled: true
  info:
      git:
          enabled: true
  endpoint:
    health:
        group:
          custom:
              include:
                  "*"
              show-components:
                  always
              show-details:
                  always
    info:
        enabled: true
    metrics:
        enabled: true

