spring:
    security:
      oauth2:
        client:
          registration:
            google:
              provider: google
              client-id: your-id
              client-secret: your-secret
              redirect-uri: http://localhost:3000/login/oauth2/code/
    datasource:
        url: jdbc:postgresql://localhost:5432/dentocrates
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
                type:
                  json_format_mapper: com.rmnnorbert.dentocrates.security.config.JacksonJsonFormatMapperCustom
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    web:
      resources:
          static-locations: classpath:/frontend/
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        operations-sorter:
            "method"
management:
  endpoints:
      web:
          exposure:
              include:
                  "*"
  health:
      db:
          enabled: true
  info:
      git:
          enabled: true
  endpoint:
    health:
        group:
          custom:
              include:
                  "*"
              show-components:
                  always
              show-details:
                  always
    info:
        enabled: true
    metrics:
        enabled: true
