spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/dentocrates
        username: ${username}
        password: ${password}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

