version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - mynetwork
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=dentocrates
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dentocrates:
    image: rmnorbert/dentocrates
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SECRET=048492546432436A442848F3147319D665857603B6B272848F751725773475237A5E567A66564
    volumes:
      - ./resources/static/dist:/app/src/main/resources/frontend
networks:
  mynetwork:
    driver: bridge
volumes:
  postgres-data:
    driver: local
