version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - mynetwork
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=dentocrates
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dentocrates:
    image: rmnorbert/dentocrates
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SECRET=048492546432436A442848F3147319D665857603B6B272848F751725773475237A5E567A66564
      - oauthId=yourOauthId
      - oauthSecret=yourOauthSecret
      - SENDER_USERNAME=yourEmail@gmail.com
    volumes:
      - ./resources/static/dist:/app/src/main/resources/frontend

  proxy:
    container_name: proxy
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-proxy
    networks:
      - mynetwork
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - dentocrates

networks:
  mynetwork:
    driver: bridge
volumes:
  postgres-data:
    driver: local
