# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app
COPY . /app

# Copy files to the container
COPY package*.json ./
COPY proxy-server.js ./
# Install dependencies
RUN npm install

# Copy the rest of your proxy server source code to the container
COPY src .

# Expose the port that your proxy server listens on (must match your proxy server configuration)
EXPOSE 3001

# Command to start your proxy server (adjust as needed for your specific setup)
CMD ["node", "proxy-server.js"]
